default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: localhost
  username: rails
  password: strongpassword

development:
  <<: *default
  database: hamara_group_development

test:
  <<: *default
  database: hamara_group_test

production:
  <<: *default
  database: hamara_group
