default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: localhost
  username: rails
  password: strongpassword

development:
  primary:
    <<: *default
    database: hamara_group_development
  queue:
    <<: *default
    database: hamara_group_development
  cable:
    <<: *default
    database: hamara_group_development

test:
  primary:
    <<: *default
    database: hamara_group_test
  queue:
    <<: *default
    database: hamara_group_test
  cable:
    <<: *default
    database: hamara_group_test

production:
  primary:
    <<: *default
    database: hamara_group
  queue:
    <<: *default
    database: hamara_group
  cable:
    <<: *default
    database: hamara_group
